version: '3.8'
services:
  backend:
    build: .
    container_name: nest-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - FRONTEND_IP=*
      - MONGO_URI=mongodb://mongo:27017/devsecops
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=devsecops
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
