services:
  backend:
    build: .
    container_name: nest-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=devsecops
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
